# docker-compose.yml
version: '3'
services:
    db:
        image: mysql
        ports:
            - 3317:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
    php:
        build: php-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ./www:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
    nginx:
        build: nginx
        ports:
            - 8000:80
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./www:/var/www/symfony
