# docker-compose.yml
services:
  db:
    image: mysql:8.3
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    ports:
      - "8000:80"

  composer:
    image: composer:2.7
    volumes:
      - ./www:/var/www
    working_dir: /var/www

  node:
    image: node:21
    volumes:
      - ./www:/var/www
    working_dir: /var/www

volumes:
  database:
