name: Unit tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6

      - name: Run unit tests
        run: vendor/bin/phpunit
